//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyBox.Models.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"USE [{0}]
SELECT	Name AS ObjectName, 
		'ASS' AS ObjectType, 
		NULL AS SchemaName, 
		Name AS FullyQualifiedName 
FROM sys.assemblies A
UNION ALL 
SELECT	O.Name AS ObjectName, 
		LTRIM(RTRIM(O.[type])) AS ObjectType, 
		S.name AS SchemaName, 
		S.name + '.' + O.name AS FullyQualifiedName
FROM sys.objects O
	WITH (NOLOCK)
INNER JOIN sys.schemas S
	WITH (NOLOCK)
ON S.schema_id = O.schema_id
WHERE type <> 'S' and type <> 'IT' ")]
        public string Query_ObjectLookup {
            get {
                return ((string)(this["Query_ObjectLookup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT\t[D].[name] AS [Name],\r\n\t\t[D].[database_id] AS [Id],\r\n\t\t[D].[state_desc] AS" +
            " [StateDescription]\r\nFROM [master].[sys].[databases] D\r\nWHERE [D].[name] NOT IN " +
            "(\'master\', \'tempdb\', \'model\', \'msdb\', \'sysdb\') AND [D].[is_distributor] = 0")]
        public string Query_Databases {
            get {
                return ((string)(this["Query_Databases"]));
            }
        }
    }
}
